### PR TITLE
Allow passing CA certificate as string

### PR DESCRIPTION
**Pull request by legoscia**
Accept `cacert` as well as `cacertfile`.

### CODE REVIEW

**Comment by aboroska** [comment]
If you don't pass the following the hostname is not checked, defeating the purpose of the CA cert.

    {customize_hostname_check,
      [{match_fun, public_key:pkix_verify_hostname_match_fun(https)}]}

It needs Erlang 21 at least though.

**Comment by aboroska** [comment]
At least `pkix_verify_hostname_match_fun` needed for wildcard certs.

**Comment by aboroska** [comment]
Also the following prevents downgrading TLS to 1.0 by ensuring 1.2 only:

    {versions, ['tlsv1.2']},

**Comment by legoscia** [comment]
Getting it to work with wildcard certs seems to make it break when the hostname in the certificate isn't all lowercase, as `public_key:pkix_verify_hostname_match_fun(https)` doesn't convert everything to lowercase before comparing

Perhaps it would be worth making TLS options more configurable, also for setting allowed versions...

**Pull request merged**
